on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-main:
    environment:
      name: github-pages
      #url: ${{ steps.build-publish.outputs.page_url }}
      url: https://graywolf13.github.io/best-password-manager/
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: public
